version: '3.8'

services:
  randomnumbervalidator:
    build:
      context: .
      dockerfile: Dockerfile
    image: randomnumbervalidator:latest
    container_name: randomnumbervalidator
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:randomvalidator@db:5432/randomvalidator
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "timeout", "2", "bash", "-c", "</dev/tcp/localhost/3000"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    # Optional: Mount volumes for persistent data (if needed)
    # volumes:
    #   - ./data:/app/data

  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: randomvalidator-db
    environment:
      - POSTGRES_PASSWORD=randomvalidator
      - POSTGRES_DB=randomvalidator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
